# my global config
global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 30s

  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - 'alert.rules'

# alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/cadvisor.yml
    job_name: 'cadvisor'

  - file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/node_exporter.yml
    job_name: 'node-exporter'
