version: '3.7'

volumes:
  data: {}
  prometheus-data: {}
  grafana_data: {}

services:
  storage:
    image: minio/minio:latest
    container_name: storage
    command: server /data --console-address ":9001"
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
        MINIO_ROOT_USER: ${Storage_AccessKey:-STORAGE_ACCESS_KEY}
        MINIO_ROOT_PASSWORD: ${Storage_Secret:-STORAGE_SECRET_KEY}
        MINIO_PROMETHEUS_AUTH_TYPE: public
    volumes:
      - data:/data
    networks:
      - minio-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    container_name: bucket
    networks:
      - minio-net
    depends_on:
      - storage
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add storage http://storage:9000 ${Storage_AccessKey-STORAGE_ACCESS_KEY} ${Storage_Secret-STORAGE_SECRET_KEY} &&
      /usr/bin/mc mb --ignore-existing storage/${Storage_Bucket:-data} &&
      /usr/bin/mc policy set download storage/${Storage_Bucket:-data} &&
      exit 0;
      "

  uploader:
    image: netology/uploader
    build: ./uploader
    container_name: uploader
    networks:
      - minio-net
    depends_on:
      - storage
      - createbuckets
    expose:
      - 3000
    environment:
      PORT: 3000
      S3_HOST: storage
      S3_PORT: 9000
      S3_ACCESS_KEY: ${Storage_AccessKey:-STORAGE_ACCESS_KEY}
      S3_ACCESS_SECRET: ${Storage_Secret:-STORAGE_SECRET_KEY}
      S3_BUCKET: ${Storage_Bucket:-STORAGE_BUCKET}

  security:
    image: netology/security
    build: ./security
    container_name: security
    networks:
      - minio-net
    expose:
      - 3000
    environment:
      PORT: 3000

  gateway:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:8080"
    networks:
      - minio-net
    ports:
      - "80:8080"
    depends_on:
      - storage
      - uploader
      - security

networks:
  minio-net:
   driver: bridge
