---
- name: Install clickhouse
  hosts: clickhouse
  roles:
    - ansible-clickhouse

- name: Install lighthouse
  become: yes
  hosts: lighthouse
  roles:
    - ansible-nginx
    - ansible-git
    - ansible-lighthouse
  tasks:
    - name: create nginx.conf
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      register: nginx_config

    - name: restart nginx
      ansible.builtin.command: nginx -s reload
      when: nginx_config.changed

- name: Install vector
  hosts: server
  roles:
    - ansible-vector
  tasks:
    - name: Vector | create config
      become: yes
      ansible.builtin.template:
        src: vector.yml.j2
        dest: /etc/vector/vector.yml
        mode: "0750"
      register: vector_config

    - name: Vector | start service
      become: yes
      ansible.builtin.service:
        name: vector
        state: restarted
      when: vector_config.changed
