---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: stage
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: news-frontend
  namespace: stage
spec:
  type: NodePort
  selector:
    app: news
  ports:
    - port: 80
      nodePort: 30080
      name: frontend
    - port: 9000
      nodePort: 30090
      name: backend