---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: prod
data:
  DB_NAME: news
  DB_URL: postgres-0
  BASE_URL: http://backend:9000
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
          root /app;
          index index.html;
          try_files $uri /index.html;
      }

      location ~* /detail {
          root /app;
          index index.html;
          try_files $uri /item.html;
      }

      location ~* /static {
          root /app;
      }
    }
