resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.


    [DOCKER_SERVERS]
    node01.netology.cloud ansible_host=${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
    node02.netology.cloud ansible_host=${yandex_compute_instance.node02.network_interface.0.nat_ip_address}

    [DOCKER_SERVERS:vars]
    ansible_ssh_private_key_file=/home/boliwar/.ssh/id_rsa_2048

    [DOCKER_SERVERS_ALL:children]
    DOCKER_SERVERS
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.node01,
    yandex_compute_instance.node02,
  ]
}
