---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: news
  name: news
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
        - image: boliwar/backend:latest
          name: backend
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/news
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: "/mp/cache"
              name: my-volume
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        - image: boliwar/frontend:latest
          name: frontend
          ports:
            - containerPort: 80
          env:
            - name: BASE_URL
              value: http://news:9000
          volumeMounts:
            - mountPath: "/static"
              name: my-volume
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: my-volume
          emptyDir: {}