---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: boliwar/backend:1.0.0
        name: backend
        env:
          - name: DATABASE_URL
            value: postgresql://postgres:postgres@postgres:5432/news
        ports:
          - containerPort: 9000